development:
  server: "https://ethifayeserver.herokuapp.com/faye"
  secret_token: "ethi"
  signature_expiration: 86400 # one hour
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://ethifayeserver.herokuapp.com/faye"
  secret_token: "ethi"
  signature_expiration: 86400 # one hour
